language: scala
scala:
- 2.12.2
jdk:
- oraclejdk8
deploy:
  provider: heroku
  app: repromptserver
  api_key:
    secure: "prRj8SJtjCGoCSvsU7kIL8XJvL588sB1P0eS8jcK7ZOrBSLDCQJ/G8ND3r/1GZ+j5spYg5MfMRk52B9XtZcRVbWfZ/w+zRT9ugcVgBB8ATSur0Q+JUcIRPpF0mDpk+OBWAARGzmE7nkiEb0XSGjd5Bh0odQ/ZU9PzO6Bv+BT3zS4g3614I2BwFZO61kNTkVOY/gZnmDZsk8sROY/DU2MZJFBwJHvzKK1sfxAMhwleyxdXAgjaONNWCaCdStT9887jqEvxzgmhA5oadNi0i6xEDGUyCxwSSF6hYturNySZrxMc5fDyv5VquNdlcFXSuNNwgKjZ2a5XygOOoLv7qIsuHmV++IUtuUGcYcLwhghJzdd1u1je1HWLtGBq+x2O73RvWwaHrbdR09zF8NkuZLfrofdIJi65X3KCKz7PNAoUNn346O2qHulf2jUtAcZOkVEw4ra2Rf40YKxZ/E69n8KYkbSyeVpQe4tSvp5K6Rb8P5QxfGVwyxK48aSXj08nYzlsXqfO1cmCARQsXA3dCsJNojKKIvYQfU8W7ZXLdjfiVsi0CU3GYzpbgZU3JAATuYe8LgbqhNRGyQEaU3OcS7TUflBAJ8kQTR68uODBaKjgYIXQfRaWLXReE9QUanvAYMetnTzZymQqnUMn7XH8QAYs0lYBLwi9N/fFckPGsGNwxk="
