language: scala
scala:
- 2.12.2
deploy:
  provider: heroku      
  app: repromptserver
  api_key:
    secure: QRIcqkGKcjIEX/4CHEWezQ5tHG60GHAdD5v3/ewzVhAXrJ2LwWiKoZg1IHRCFw5774pjXNp9CyvvTvn36So8cV4fTEkgabyYa7MgN17zvHeutxfr0aMVagV12OtQOA1L/y97+VMiQXPjSkS/dOniHgOeo2mHP0zhGZHOJb4Nd/tooX5uwXlPB0TMr+dshbV+H2jzhOhWvVgkJry44iYtuSGehFvOH3bwIlzdOG1ziiVxWMC7oUYMOOD9dPc4bvGBGN9gj/ASchWWFfw2XW1c2WTC3t5bAuGNKw44EYsYg1NaCgOdZiEJxr9B5YJCa5i9p2VRHHEIYX0VHzLKTprBhj3j37/RuisfdwjUAYp8MLCJJa9DDOd3o9+x02QQ0Sf5fKbOeEaDUZSPGHIkR9o509dovzVYZ3aWEl9t2b25z/V8i0HJt1Yk3eQ5tn4sAmU3ionhBUXIpO5N5FfgFviDfC6l5pPWq72jS9pnJ5Y3d2zusF1rRkY9kiKOw46HDt1kfbBRHIoCIIxmYkA+fWRy2PAuuVNhbqBfs5xkDy+/EkBeXcEWYCrkGQFSOWQ/0Fp+rkK1RIWeTZylkG5FlNMYqREtCi0eZ5tFIxSyxIIvY65vFp6g6guKGyMoc4cb9VXw0nzS8irVgNBniW9prS7EV/pyKgEXFgLCJ4O2hz5I/yc=
