language: scala
scala:
- 2.12.2
jdk:
- oraclejdk8
deploy:
  provider: heroku
  app: repromptserver
  api_key:
    secure: "gb9KN2QQeO/PaOxaQToqvDwfBfXFcgCtkiMKEm8IL36tihO/IRAXI23lVU/H60LK+aQcf0GEjUhHAfS4aj/5TZz6DR1sS+6uoMmHwRBTgYOJp4OfUhKdaLmsDv3pMjRs4vUbkGBjRh8KElefMuSpF2/Hw9a7nSwuiwyOa88AyZsz/DetP32CbjeEHkFfpRoVkmePqrFP9gIvh3hXt7Tdd6pWISWzFjD+e/I7M8L0ujb2tVg0DtiOxuaavVPYvmwyQM+NifwKWiZg0vg7pIMZoNZcEMGPOxkxo1DJlOe4HumLYSxQpPa7tKtQD0HV9H6ep4Itzx/TxvivlUQWvUqr0Z5fvrHsK81kqcYo6jF2EtlNQWOUhB7ZLYnv9PsXJMa4/cRTd01NMdd1MJ7E/wlCUuyCuJmRjSslsVtzIcmweUIrhOOXrXTb9hJJsyoJ07KUek/bcoUfzfZDcpmO9uAIhvmrL06AeUkM6jlQEdfGHcuvTGEgSXEe8fc+IB6+HpGAZ4cras0jQjz6VQ0L4QY5P73BVBRljT4zZ5qazxP7KhXt8IaQ5sCxmOe+YIpL+u0fYF8tPQj+ZaefQ9xPQiOS63r+PFc4ZNY7luse+Qea13CMfeR/SRfbluFYVaPEC1+5s7c9sBRwjvRiZ0rp9/OjIdHUMlXGIKy5XQaE5oOXyG0="