language: scala
scala:
- 2.12.2
jdk:
- oraclejdk8
deploy:
  provider: heroku
  app: repromptserver
  api_key:
    secure: hl7v8VIdNj77bTGNGhr3UagXll5c+LSLYvxw+MGkbzhsMTIc1e84P29HZii0PYUIaoH+Fv8zVHm4Hlq8qcIhqc88V0uJSZaoOKc/t05753XinVMyDETJlzJP8VQoVA+8fyf9BN759bbS24IZ+uhzm5Dq5KKqNR8aWubryi0yHpk2BSDiCVwXAIV5TG9jIaM6V1V86wfP4OecCJZ0R03v2tu4ReajNDZ7NRPJYFmupdWE1AStEePnXXQlGSooBh3z1WYeS+pdYJS/kPu09kV6uu3ITDj+tivbJgH1gMTiHsXEMe46T2U/uo9ct59RX+M8LvsXS+bSRA/jBMvI6MZVadwMuazlv1E4iNe5oGBgM4jZXZppG/vrkdThzOxe3Wd0uVW45xM/Y8wViz/k5J9TrLj6MnFrRAX7zdhNR8MgzRJ4/fS2PRb4lSJxGaKyrLbDar0NkH/TeS7V4WH4/bIty4HdIzKbXqiKltzg732lmk8G2m1eSj7+yQGU5rZmnFjH7dTe7H0Yu+mhJaRJZAh3ZehI168bQBjhqdsDtkw/EA7goD23otVdT73HyTjw24rg4jSJZn9B+HuJhTgo6T98KDkRzNdy19xdhkKoea2KQ1d1shrRYp8dYvs5JCpKqiuj/a8gURijZtp0jydJ1KPXdn1O3gDRoH5qZT0gPPnUu0M=
